# _config.yml

# 1. Réglage global des permaliens
#   /:title/ sert à transformer video_portrait.html en /video_portrait/
permalink: /:title/

# 2. (Optionnel) Choisir un thème GitHub Pages si tu veux bénéficier d'un style par défaut
# theme: minima

# 3. Exclure ce dossier s’il en gêne Jekyll
exclude:
  - manifest.json
  - CNAME
  - assets/images
